import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";
// import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aidan's Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="w-screen h-screen bg-scroll bg-gradient-to-b from-blue-50 to-red-100 overflow-y-auto">
//           {/* HEADER */}
//           <div className="h-24">
//             <Navbar />
//           </div>
//           {/* MAIN CONTENT */}
//           <div className="h-[calc(100vh-6rem)] mt-1">
//             {children}
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
